apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hermes

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - service.yaml
  - virtualservice.yaml
  - deployment.yaml
  - sealed-secrets.yaml
  - sealed-github.yaml
  - keda-http.yaml

# Secrets sellados vía Bitnami Sealed Secrets
# Los valores originales SOLO existen en Kubernetes, nunca en git
