apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: hermes-vs
  namespace: hermes
  labels:
    app.kubernetes.io/name: hermes-agent
    app.kubernetes.io/part-of: hermes
spec:
  hosts:
    - hermes.kdvops.com
  gateways:
    - istio-system/kdvops-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
            port:
              number: 8080
